INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:10/18/2021, 13:29:48, Accesing metrics
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:29:48] "[37mGET /metrics HTTP/1.1[0m" 200 -
ERROR:app:Exception on /healthz [GET]
Traceback (most recent call last):
  File "d:\Data Science\Courses\Udacity\Cloud Native\Project 1\nd064_course_1-main\project\techtrends\app.py", line 112, in health
    if len(post)>0:
TypeError: object of type 'function' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Data Science\Courses\Udacity\Cloud Native\Project 1\nd064_course_1-main\project\techtrends\app.py", line 121, in health
    response = response(status=500,result="ERROR - unhealthy")
UnboundLocalError: local variable 'response' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\home\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\Data Science\Courses\Udacity\Cloud Native\Project 1\nd064_course_1-main\project\techtrends\app.py", line 125, in health
    response = response(status=500,result="ERROR - unhealthy")
UnboundLocalError: local variable 'response' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:29:54] "[35m[1mGET /healthz HTTP/1.1[0m" 500 -
ERROR:app:Exception on /healthz [GET]
Traceback (most recent call last):
  File "d:\Data Science\Courses\Udacity\Cloud Native\Project 1\nd064_course_1-main\project\techtrends\app.py", line 112, in health
    if len(post)>0:
TypeError: object of type 'function' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Data Science\Courses\Udacity\Cloud Native\Project 1\nd064_course_1-main\project\techtrends\app.py", line 121, in health
    response = response(status=500,result="ERROR - unhealthy")
UnboundLocalError: local variable 'response' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\home\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\Data Science\Courses\Udacity\Cloud Native\Project 1\nd064_course_1-main\project\techtrends\app.py", line 125, in health
    response = response(status=500,result="ERROR - unhealthy")
UnboundLocalError: local variable 'response' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:30:14] "[35m[1mGET /healthz HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:30:19] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:30:19] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /healthz [GET]
Traceback (most recent call last):
  File "d:\Data Science\Courses\Udacity\Cloud Native\Project 1\nd064_course_1-main\project\techtrends\app.py", line 112, in health
    if len(post)>0:
TypeError: object of type 'function' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Data Science\Courses\Udacity\Cloud Native\Project 1\nd064_course_1-main\project\techtrends\app.py", line 121, in health
    response = response(status=500,result="ERROR - unhealthy")
UnboundLocalError: local variable 'response' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\home\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\Data Science\Courses\Udacity\Cloud Native\Project 1\nd064_course_1-main\project\techtrends\app.py", line 125, in health
    response = response(status=500,result="ERROR - unhealthy")
UnboundLocalError: local variable 'response' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:30:31] "[35m[1mGET /healthz HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /healthz [GET]
Traceback (most recent call last):
  File "d:\Data Science\Courses\Udacity\Cloud Native\Project 1\nd064_course_1-main\project\techtrends\app.py", line 112, in health
    if len(post)>0:
TypeError: object of type 'function' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Data Science\Courses\Udacity\Cloud Native\Project 1\nd064_course_1-main\project\techtrends\app.py", line 121, in health
    response = response(status=500,result="ERROR - unhealthy")
UnboundLocalError: local variable 'response' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\home\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\Data Science\Courses\Udacity\Cloud Native\Project 1\nd064_course_1-main\project\techtrends\app.py", line 125, in health
    response = response(status=500,result="ERROR - unhealthy")
UnboundLocalError: local variable 'response' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:31:25] "[35m[1mGET /healthz HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /healthz [GET]
Traceback (most recent call last):
  File "d:\Data Science\Courses\Udacity\Cloud Native\Project 1\nd064_course_1-main\project\techtrends\app.py", line 114, in health
    if len(post)>0:
TypeError: object of type 'function' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Data Science\Courses\Udacity\Cloud Native\Project 1\nd064_course_1-main\project\techtrends\app.py", line 123, in health
    response = response(status=500,result="ERROR - unhealthy")
UnboundLocalError: local variable 'response' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\home\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\home\anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\Data Science\Courses\Udacity\Cloud Native\Project 1\nd064_course_1-main\project\techtrends\app.py", line 128, in health
    response = response(status=500,result="ERROR - unhealthy")
UnboundLocalError: local variable 'response' referenced before assignment
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:32:37] "[35m[1mGET /healthz HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:10/18/2021, 13:33:36, unhealthy
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:33:36] "[35m[1mGET /healthz HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:10/18/2021, 13:33:59, unhealthy
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:33:59] "[35m[1mGET /healthz HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:10/18/2021, 13:36:38, Healthy
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:36:38] "[37mGET /healthz HTTP/1.1[0m" 200 -
INFO:app:10/18/2021, 13:37:09, Accesing metrics
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:37:09] "[37mGET /metrics HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:10/18/2021, 13:38:17, Healthy
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:38:17] "[37mGET /healthz HTTP/1.1[0m" 200 -
INFO:app:10/18/2021, 13:38:42, Accesing metrics
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:38:42] "[37mGET /metrics HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:10/18/2021, 13:39:51, Accesing metrics
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:39:51] "[37mGET /metrics HTTP/1.1[0m" 200 -
INFO:app:10/18/2021, 13:39:53, unhealthy
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:39:53] "[35m[1mGET /healthz HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:40:01] "[37mGET /create HTTP/1.1[0m" 200 -
INFO:app:10/18/2021, 13:40:05, A new article "aa" is created.
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:40:05] "[32mPOST /create HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:40:05] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:40:07] "[37mGET /create HTTP/1.1[0m" 200 -
INFO:app:10/18/2021, 13:40:09, unhealthy
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:40:09] "[35m[1mGET /healthz HTTP/1.1[0m" 500 -
INFO:app:10/18/2021, 13:40:16, Accesing metrics
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:40:16] "[37mGET /metrics HTTP/1.1[0m" 200 -
INFO:app:10/18/2021, 13:40:19, unhealthy
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:40:19] "[35m[1mGET /healthz HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:app:10/18/2021, 13:40:47, unhealthy
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:40:47] "[35m[1mGET /healthz HTTP/1.1[0m" 500 -
INFO:app:10/18/2021, 13:40:50, unhealthy
INFO:werkzeug:127.0.0.1 - - [18/Oct/2021 13:40:50] "[35m[1mGET /healthz HTTP/1.1[0m" 500 -
